### ISSUE TITLE
Contract Checklist

### ISSUE THREAD

**Issue by travisdmathis** [pandao-bamboo/contracts#1]
**Insurance Pool Factory**
- [x] Only Owner(DAO Voting Agent) Can Create an Insurance Pool
- [x] Can Register an Insurance Pool

**When registering a pool can set the following details**
- [x] insuredTokenAddress
- [x] insureeFeeRate
- [x] serviceFeeRate(DAO)
- [x] (insureeFeeRate - serviceFeeRate) = insurerFee
- [x] earlyClaimPenalty

**When Insurance Pools are created:** 
- [ ] Create Collateral Pool(Unlocked Collateral)
- [ ] Create Claims Pool(Locked Claims Pool)

**When insurer adds collateral to an insurance pool**
- [ ] Create `collateralTokens` at a 1:1 ratio and send them to the insurer
- [ ] Also approve the `collateralTokens` to be transferred back to the `collateralPoolAddress`
- [ ] `collateralTokens` are redeemable for the unlocked collateral in the pool at any time as it has not been matched with an insuree

**When a insuree is matched with an insurer**
- [ ] Insurer transfers the proper `collateralToken` amount back to the `collateralPool`
- [ ] Burn the `collateralTokens` when they are received by the `collateralPool`
- [ ] Transfer `claimTokens` to the `insurerAddress` at a 1:1 ratio
- [ ] `claimTokens` are redeemed for the value + premium at the end of the insurance contract
- [ ] burn `claimTokens` on redemption
- [ ] a `claimToken` can be redeemed early and matched with a new insurer but the original insurer suffers a X% haircut on premium paid to the DAO for finding a new insurer for the contract.
- [ ] Wallet X can Insure Wallet Y for N amount of Z token
